
language: python
python: 2.7
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py27
before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  - codecov

